"""
WLTS QGIS Plugin.

Python QGIS Plugin for Web Land Trajectory Service.
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/.
                              -------------------
begin                : 2019-05-04
git sha              : $Format:%H$
copyright            : (C) 2021 by INPE
email                : brazildatacube@dpi.inpe.br

This program is free software.

Python QGIS Plugin for Web Land Trajectory Service.
You can redistribute it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
Copyright (C) 2019-2021 INPE.
"""


import os

from qgis.PyQt import QtWidgets, uic

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wlts_qgis_dialog_base.ui'))

class WltsQgisDialog(QtWidgets.QDialog, FORM_CLASS):
    """Set up the user interface from Designer through FORM_CLASS.

    :param QDialog: QDialog
    :param FORM_CLASS: Set gui
    """

    def __init__(self, parent=None):
        """Build UI element.

        :param parent: None
        """
        super(WltsQgisDialog, self).__init__(parent)
        self.setupUi(self)
