"""
WLTS QGIS Plugin.

Python QGIS Plugin for Web Land Trajectory Service.
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/.
                              -------------------
begin                : 2019-05-04
git sha              : $Format:%H$
copyright            : (C) 2020 by INPE
email                : brazildatacube@dpi.inpe.br

This program is free software.

Python QGIS Plugin for Web Land Trajectory Service.
You can redistribute it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
Copyright (C) 2019-2021 INPE.
"""


import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))