# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WltsQgis
                                 A QGIS plugin
 Web Land Trajectory Service
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-31
        git sha              : $Format:%H$
        copyright            : (C) 2020 by INPE
        email                : brazildatacube@inpe.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
