# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Python Client Library for Web Land TrajectoryService
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-04
        copyright            : (C) 2020 by INPE
        email                : brazildatacube@dpi.inpe.br
        git sha              : $Format:%H$
 ***************************************************************************/
"""

import os


# Class to configure global variables used in source code

BASE_DIR = os.path.abspath(os.path.dirname(__file__))