# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Python Client Library for Web Land Trajectory Service
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-18
        copyright            : (C) 2020 by INPE
        email                : brazildatacube@dpi.inpe.br
        git sha              : $Format:%H$
 ***************************************************************************/
"""

__version__ = '0.4.0-0'