"""
WLTS QGIS Plugin.

Python QGIS Plugin for Web Land Trajectory Service.
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/.
                              -------------------
begin                : 2019-05-04
git sha              : $Format:%H$
copyright            : (C) 2020 by INPE
email                : brazildatacube@dpi.inpe.br

This program is free software.

Python QGIS Plugin for Web Land Trajectory Service.
You can redistribute it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
Copyright (C) 2019-2021 INPE.
"""

import csv
import json
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


class FilesExport:
    """Exporting WLTS data in different formats.

    :Methods:
        defaultCode
        generateCode
        generateCSV
        generateJSON
        generatePlotFIG
    """

    def defaultCode(self):
        """Return a default python code with blank WLTS parameters."""
        template = (
            Path(os.path.abspath(os.path.dirname(__file__)))
                / 'examples'
                    / 'trajectory_export_template.txt'
        )
        return open(template, 'r').read()

    def generateCode(self, file_name, attributes):
        """Generate a python code file filling WLTS blank spaces.

        :param file_name<str>: file to save path
        :param attributtes<dict>: {
            "host"<str>: the chosen WLTS host
            "collections"<tuple>: the list of selected bands
            "coordinates"<dict>: {
                "crs"<str>: the projection of Latitude and Longitude of Point
                "lat"<float>: selected Latitude
                "long"<float>: selected Longitude
            }
            "time_interval"<dict>: {
                "start_date"<str>: defining start of time interval in string format <yyyy-MM-dd>
                "end_date"<str>: defining end of time interval in string format <yyyy-MM-dd>
            }
        }
        """
        try:
            collections_string = attributes.get("collections")
            lat = "{:,.2f}".format(attributes.get("lat"))
            lon = "{:,.2f}".format(attributes.get("long"))
            mapping = {
                "service_host": attributes.get("host"),
                "collections": collections_string,
                "latitude": lat,
                "longitude": lon,
                "start_date": attributes.get("start"),
                "end_date": attributes.get("end")
            }
            code_to_save = self.defaultCode().format(**mapping)
            file = open(file_name, "w")
            file.write(code_to_save)
            file.close()
        except FileNotFoundError:
            pass

    def generateCSV(self, file_name, trajectory):
        """Generate a CSV file with trajectory data.

        :param file_name<str>: file to save path.
        :param trajectory<dict>: the trajectory reponse dictionary.
        """
        try:
            df = trajectory.df()
            dict = {}
            latlng = [
                trajectory.get('query').get('latitude'),
                trajectory.get('query').get('longitude')
            ]
            for key in list(df.keys()):
                line = []
                for i in range(len(df[key])):
                    line.append(df[key][i])
                dict[key] = line
            latitude = []
            longitude = []
            for i in range(len(df)):
                latitude.append(latlng[0])
                longitude.append(latlng[1])
            dict['latitude'] = latitude
            dict['longitude'] = longitude
            output = pd.DataFrame.from_dict(dict)
            output.to_csv(file_name, sep=';', index=False, header=True)
        except FileNotFoundError:
            pass

    def generateJSON(self, file_name, trajectory):
        """Generate a JSON file with trajectory data.

        :param file_name<str>: file to save path.
        :param trajectory<dict>: the trajectory service reponse dictionary.
        """
        try:
            with open(file_name, 'w') as outfile:
                json.dump(trajectory, outfile)
        except FileNotFoundError:
            pass

    def generatePlotFig(self, trajectory):
        """Generate an image .JPEG with trajectory data in a table.

        :param trajectory<dict>: the trajectory service reponse dictionary.
        """
        try:
            plt.clf()
            plt.cla()
            plt.close()
            fig = plt.figure(figsize=(8, 5))
            df_trajectory = trajectory.df().drop(columns="geom")
            ax2 = fig.add_subplot()
            font_size = 18
            bbox = [0, 0, 1, 1]
            ax2.axis('off')
            mpl_table = ax2.table(
                cellText=df_trajectory.values,
                rowLabels=df_trajectory.index,
                bbox=bbox,
                colLabels=df_trajectory.columns
            )
            mpl_table.auto_set_font_size(True)
            mpl_table.set_fontsize(font_size)
            plt.show()
        except:
            pass
